services:
  node-container:
    image: node:20-alpine
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./coc-bot/:/app/
    command: bash -c "npm install && node --env-file=.env src/index.js"
    networks:
      - discord_server
    restart: unless-stopped

networks:
  discord_server:
    name: discord_server
    external: true
