services:
  node-container:
    image: node:20-alpine
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./coc-bot/:/app/
    command: ["tail", "-F", "/dev/null"]
    networks:
      - discord_server

networks:
  discord_server:
    name: discord_server
    external: true
